### ISSUE TITLE
Possibility to access prometheus via data source

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#1]
Hi,
is it possible to configure and access your prometheus data on existing grafana installations?
I have already an instance running and it will be great if I can only add another dashboard.

Thanks JO!

**Comment by cinemast** [comment]
Hi!

I changed the configuration so that the prometheus endpoint is publicly available under https://covid19.spiessknafl.at/prometheus. You should be able to add this URL as a datasource for your Grafana dashboards.

Let me know if this works for you. Otherwise I could give you a dump of the prometheus data.

**Comment by cinemast** [comment]
Also, if you have a cool dashboard you would like to share, I can easily add it to my instance.

**Comment by jostrasser** [comment]
Hi!
Thanks! The data source is working!
Sure, I will start to build a dashboard now which I can also share with you ;)
I'll keep you posted.

Thanks JO!

**Comment by jostrasser** [comment]
Hi,
Is it possible to add localization data (LAT/LONG) to the Prometheus DB?

This data is needed to implement a map view into the dashboard. 

I have seen that the Data Repository by Johns Hopkins CSSE can deliver it. 

I think this data would also be a great source because the update frequency is higher. 

https://github.com/CSSEGISandData/COVID-19

BR/JO!

**Comment by cinemast** [comment]
I just had a look at the data. It lacks details for Austria (Bundesland) and is also older than the information from [BMSGPK](https://www.sozialministerium.at/Informationen-zum-Coronavirus/Neuartiges-Coronavirus-(2019-nCov).html). 

The lat/long thing is a good idea.

**Comment by jostrasser** [comment]
Jep, You are right. Maybe you can merge the data to get the coordinates for the map?

**Comment by jostrasser** [comment]
...and another Feature Request: a timestamp to track the update times :) Thanks JO!

**Comment by cinemast** [comment]
lat/long is included now.
