### ISSUE TITLE
cov19_world_death continent missing

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#10]
Hi,

Since now the continent value is missing in almost all rows in the cov19_world_death stats. 
That is the reason why the stats panels are showing an incorrect value. 

The value of infected persons is also not correct.

Thanks JO

**Comment by jostrasser** [comment]
Only data of ECDC is affected.

**Comment by cinemast** [comment]
They fixed it again. I fixed the parsing from info.gesundheitsministerum.at as well.

**Comment by jostrasser** [comment]
Great, thank you. 

BR/JO!

**Comment by jostrasser** [comment]
Is it possible for you to remove the wrong data from the database?

It would be great to get a correct line on the continent overview graphs.
Right now the line drops yesterday at 15:30.

Thanks JO!

**Comment by cinemast** [comment]
Do you have a prometheus-query at hand which returns the datapoints you want to delete?

**Comment by jostrasser** [comment]
> Do you have a prometheus-query at hand which returns the datapoints you want to delete?

No sorry, unfortunately I don't have Prometheus know-how.

I only can give you the exact time frame which is not correct and should be deleted (if possible):
2020-03-30 13:00 - 2020-03-31 14:30

I think a database backup would be useful before you run a truncate on the database ;)

Thanks JO!
