### ISSUE TITLE
NO DATA for all the Austrian metrics

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#12]
Hi,

all metrics are gone because the Sozialministerium has changed their dashboard:
https://info.gesundheitsministerium.at/

But now there is a CSV download with all the data available:
https://info.gesundheitsministerium.at/data/data.zip

Can you please integrate this data in your database please?
Otherwise the grafana dashboard is unusable.

Thanks JO!

**Comment by cinemast** [comment]
Sorry, I don't have time for this within the next few days. I will have a look at this on the weekend.

**Comment by jostrasser** [comment]
> Sorry, I don't have time for this within the next few days. I will have a look at this on the weekend.

ok, great, thank you!

**Comment by cinemast** [comment]
Fixed

**Comment by jostrasser** [comment]
Hi @cinemast 
the detail_dead and detail_healed data is "unknown", right now there are no correct province stats:

cov19_detail_dead{country="Austria",province="unknown"} 8.000000
cov19_detail_healed{country="Austria",province="unknown"} 360.000000
cov19_detail_dead{country="Austria",province="unknown"} 12.000000
cov19_detail_healed{country="Austria",province="unknown"} 1950.000000
cov19_detail_dead{country="Austria",province="unknown"} 86.000000
cov19_detail_healed{country="Austria",province="unknown"} 2021.000000
cov19_detail_dead{country="Austria",province="unknown"} 48.000000
cov19_detail_healed{country="Austria",province="unknown"} 1041.000000
cov19_detail_dead{country="Austria",province="unknown"} 31.000000
cov19_detail_healed{country="Austria",province="unknown"} 1011.000000
cov19_detail_dead{country="Austria",province="unknown"} 108.000000
cov19_detail_healed{country="Austria",province="unknown"} 2982.000000
cov19_detail_dead{country="Austria",province="unknown"} 98.000000
cov19_detail_healed{country="Austria",province="unknown"} 755.000000
cov19_detail_dead{country="Austria",province="unknown"} 14.000000
cov19_detail_healed{country="Austria",province="unknown"} 1748.000000
cov19_detail_dead{country="Austria",province="unknown"} 110.000000

**Comment by jostrasser** [comment]
Do you have take a look to CSV files?
Would it be easier for you to push this data into the prometheus DB?

**Comment by jostrasser** [comment]
...and at the following values the comma is on the wrong position:

cov19_tests 221.089000 (should be 221089.000)
cov19_healed 12.103000 (should be 12103.000)

**Comment by cinemast** [comment]
I fixed it, thanks.

Prometheus does not work that way. You cannot insert data from the past. So it does not make sense for me. This would be a completely differnt project then.

**Comment by jostrasser** [comment]
Thanks!

I understand... U´re right. That make not sense.

BR/JO!
