### ISSUE TITLE
Prometheus does not deliver data

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#14]
fyi...

...and your Demo Setup is also affected. https://covid19.spiessknafl.at

I get really often "No data" for many views the last few 2 weeks.
Looks identical to your Demo Setup.

BR/JO!

**Comment by jostrasser** [comment]
take a look to the collection instabilities:
https://snipboard.io/STesja.jpg

BR/JO!

**Comment by cinemast** [comment]
Should be fixed. Ministry changed their file structure again.

**Comment by jostrasser** [comment]
Great, thanks for your help. BR/JO!

**Comment by cinemast** [comment]
Its about time you start learning go and offer PRs xD

**Comment by jostrasser** [comment]
;)
