### ISSUE TITLE
Prometheus database slowness

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#15]

**Comment by jostrasser** [comment]
Hi @cinemast 
The database is really slow the last few days. Can you please check the performance of it?
Sometimes the dashboards have to refresh multiple times to get the data.
Thanks JO!

**Comment by cinemast** [comment]
Hi! I downgraded the server a few days ago, since my google credits run out this week. I am not sure yet if I will migrate to another server.

Do you find this project still useful?

**Comment by jostrasser** [comment]
Hi!

ah, I understand.
I have changed some graphs to reduce the load on the database, and it okay now.

Sure, this project is really cool and brings a good overview for AT.
I am using it on global dashboards.

It would be a great pity if you did not pursue it further.

BR/JO
