### ISSUE TITLE
Demo Setup

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#17]
Hi,
Is there a special reason why you shut down the demo setup?

Can I assist you with resources? 
Or is it possible to get an export/backup of the demo prometheus database?

Otherwise I will loose all the historical data. 

Thanks JO

**Comment by cinemast** [comment]
Hi! I do have a backup, send me a private mail and I will provide you with a download link.

**Comment by jostrasser** [comment]
Mail sent. Thanks :)
