### ISSUE TITLE
Grafana Dashboard Updates (English and German version)

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#4]
Hi!

I have updated the dashboards (Revision 5).
Could you update it in your build please.

Thanks JO!

**Comment by cinemast** [comment]
I imported them:

https://covid19.spiessknafl.at/d/eS-fSwXWz/covid-19-global-overview?orgId=1&refresh=1m
https://covid19.spiessknafl.at/d/2fa2-Y_Wz225/covid-19-globale-ubersicht?orgId=1&refresh=1m

**Comment by jostrasser** [comment]
Great! Thanks!

BR/JO!

**Comment by jostrasser** [comment]
Hi!

I have updated the dashboards (Revision 8).
Could you update it please. :)

Thanks JO!

**Comment by cinemast** [comment]
I could only find the english version, but it is imported.

**Comment by cinemast** [comment]
Nevermind, found it. Could you please change the ID of the dashboard in the german version? It collides with mine. 

Have you considered uploading yours to https://grafana.com/grafana/dashboards?
This would make things a bit easier.

**Comment by jostrasser** [comment]
> Nevermind, found it. Could you please change the ID of the dashboard in the german version? It collides with mine.
> 
> Have you considered uploading yours to https://grafana.com/grafana/dashboards?
> This would make things a bit easier.

Is is not possible for you to generate a new ID while importing the dashboard?
I haven´t yet but is a good idea. I will check that.

Thanks!
