### ISSUE TITLE
Add stats for recovered persons

### ISSUE THREAD

**Issue by cinemast** [cinemast/covid19-at#7]
Maybe use this: https://covid19.mathdro.id/api/recovered
https://github.com/mathdroid/covid-19-api

**Comment by jostrasser** [comment]
Can you deliver this data via your prometheus DB?

**Comment by cinemast** [comment]
That is the plan, yes.

**Comment by jostrasser** [comment]
any updates on this?

**Comment by cinemast** [comment]
This query should give you the results: `sum(cov19_world_recovered) by (country)`

**Comment by jostrasser** [comment]
thanks!
