### ISSUE TITLE
Keep last value of "healed in AT"

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#8]
Hi,

The Sozialministerium is removing sometimes the "healed person" values from their website.
Is it possible to keep the last known value in the prometheus database?

Otherwise the stats field will show "no data".

Thanks JO!

**Comment by cinemast** [comment]
Thanks! Good idea.

**Comment by jostrasser** [comment]
Great! Thanks! :)

**Comment by jostrasser** [comment]
Hi,

There is now a maintenance on „info.gesundheitsministerium.at“.
Since this maintenance many stats of the dashboards are showing „no data“.

I think it would be a good idea to keep the last value of ALL stats in the database if the source cannot deliver any data.

BR/JO!

**Comment by cinemast** [comment]
At the moment I don't want to do this, since I am already seeing a lot of traffic, and this would result in "non-instant" queries, meaning that the traffic is actually about 10x as much.

If it is broken until tomorrow, I will think of something else.

**Comment by jostrasser** [comment]
It's broken since more than 12 hours ;)

**Comment by jostrasser** [comment]
Okay, now there is a new site with the data for hospitalized and intensive care:

https://www.sozialministerium.at/Informationen-zum-Coronavirus/Dashboard/Zahlen-zur-Hospitalisierung

They have removed it from the Info map.

**Comment by cinemast** [comment]
Just pushed it.

**Comment by jostrasser** [comment]
Great, thank you!
