### ISSUE TITLE
Deletion of wrong data in prometheus DB

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#9]
Hi,

I have found a wrong line in the DB which is causing wrong statistics in the "COVID-19 Deaths in AUSTRIA by PROVINCE" view:

cov19_detail_dead{country="Austria",province=""} 1.000000

Can you delete it from the dataset?

Thanks!
BR/JO!

**Comment by cinemast** [comment]
Should be removed.

**Comment by jostrasser** [comment]
> Should be removed.

Nope, sorry. 
Today morning the value was „1“, now it is „4“.

**Comment by cinemast** [comment]
Please check again.

**Comment by jostrasser** [comment]
looks better now. Thanks!
